### ISSUE TITLE
Add suport for unsupported CPU's

### ISSUE THREAD

**Issue by startergo** [lzhoang2801/Hardware-Sniffer#10]
11th generation and higher CPU's can be spoofed via:

>Note

For Intel Tiger Lake and newer (11th Gen and newer), you can follow the Dortania install guide for [Comet Lake](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html).

You'll need to spoof your CPU as Comet Lake by using the below CPUID patch:

Kernel:
  Emulate:
    Cpuid1Data: Data | <55 06 0A 00 00 00 00 00 00 00 00 00 00 00 00 00>
    Cpuid1Mask: Data | <FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00>
Add this to the config.yml file under the Kernel -> Emulate section or manually to the generated config.plist file under EFI/OC/config.plist.

See [Cpuid1Data](https://github.com/Qonfused/OCE-Build/blob/main/docs/schema.md#kernel---emulate---cpuid1data) for other available CPUID patches for better XCPM support.

Below is a list of supported CPU generations and their initial and latest supported macOS versions:

**Comment by lzhoang2801** [comment]
What? For OpCore Simplify? See it https://github.com/lzhoang2801/Hardware-Sniffer/blob/main/Scripts/datasets/cpu_data.py, https://github.com/lzhoang2801/OpCore-Simplify/blob/main/Scripts/datasets/cpu_data.py

**Comment by startergo** [comment]
I am just saying that the utility will not proceed:
```
####################################################################
#                      Compatibility Checker                       #
####################################################################

1. CPU:
   - 11th Gen Intel(R) Core(TM) i7-1185G7: Up to macOS Sequoia 15
2. GPU:
   - Intel(R) Iris(R) Xe Graphics: Unsupported
      - Connected Monitor: SHP1513 (Internal)


No compatible GPU card for macOS was found!
```

**Comment by lzhoang2801** [comment]
Do you see the message 'No compatible GPU card'? And '11th Gen Intel(R) Core(TM) i7-1185G7: Up to macOS Sequoia 15'? What exactly are you trying to point out as incorrect when, in essence, you don't understand anything?

**Comment by startergo** [comment]
I was not trying to point out anything just asking to add support for unsupported CPU without realizing it is complaining about the GPU as they lie on the same chip. No need to be rude.

**Comment by lzhoang2801** [comment]
Understand that the issue you're facing is that the GPU is not supported, not the CPU as you mentioned. The problem here is simply reading comprehension.

<img width="1057" alt="Screenshot 2024-11-30 at 12 50 23" src="https://github.com/user-attachments/assets/ec004cbe-b290-4666-8b89-3ebb01db2bb2">

**Comment by lzhoang2801** [comment]
I also have no idea what unsupported CPU issue you're referring to, especially when the Compatibility Checker clearly states 'Up to macOS Sequoia 15.' Make sure you're clear-headed enough

**Comment by startergo** [comment]
I already explained my mistake. Was I not clear?
