### ISSUE TITLE
Hardware Sniffer being reported as malware 

### ISSUE THREAD

**Issue by lcsjandrey** [lzhoang2801/Hardware-Sniffer#3]
I was able to run it yesterday successfully without any prompts from Windows Defender but today it detected as a trojan. I also uploaded the file to virustotal and a few antiviruses have also reported as malware. Please see screenshot
![Capture](https://github.com/user-attachments/assets/6fe0efd6-422a-4b28-8483-b826145c9c8b)

**Comment by lzhoang2801** [comment]
Hardware Sniffer is always considered 'malware' due to the lack of a valid signature, but all the code and the executable build process have been automated by GitHub Actions, so anyone with knowledge can be sure it does nothing beyond its intended function

**Comment by lzhoang2801** [comment]
A similar result is available in the latest release. Thank you for noticing this.

[VirusTotal](https://www.virustotal.com/gui/url/a469596c27491b96f6c8d96d8e73ef2da447d6f8d2c3eb0982785368d23e6835?nocache=1)
