### ISSUE TITLE
Every time I use Hardware-Sniffer-CLI.exe again, it will re-download ACPI Binary Tools. Can I set it to call it from the same directory?

### ISSUE THREAD

**Issue by VToime** [lzhoang2801/Hardware-Sniffer#4]
![1](https://github.com/user-attachments/assets/26fca757-8443-432c-9e35-140cf47bfd7a)

**Comment by lzhoang2801** [comment]
I'm not sure you need to do that manually unless there is an error screen

**Comment by lzhoang2801** [comment]
And the Hardware Sniffer is already integrated into OpCore Simplify, so manually using the hardware sniffer is unnecessary. https://github.com/lzhoang2801/OpCore-Simplify#-how-to-use

**Comment by VToime** [comment]
> 而且硬件嗅探器已经集成到 OpCore Simplify 中，因此无需手动使用硬件嗅探器。https://github.com/lzhoang2801/OpCore-Simplify#-how-to-use

I know, I just want to say that if I use Hardware-Sniffer alone, it has the problem of needing to re-download ACPI Binary Tools every time I reopen it.

**Comment by VToime** [comment]
> 您可以尝试使用 https://github.com/lzhoang2801/Hardware-Sniffer/releases/download/1.4.1/Hardware-Sniffer.exe 吗？此问题可能是由于获取 ACPI 二进制工具的下载链接时出错

There is no error, I just want to express that on the same computer, the first time I open it and use Dump ACPI Tables, I need to download ACPI Binary Tools. The second time I open it and use Dump ACPI Tables, it still needs to be downloaded.

**Comment by VToime** [comment]
> 您可以尝试使用 https://github.com/lzhoang2801/Hardware-Sniffer/releases/download/1.4.1/Hardware-Sniffer.exe 吗？此问题可能是由于获取 ACPI 二进制工具的下载链接时出错

There is no error, I just want to express that on the same computer, the first time I open it and use Dump ACPI Tables, I need to download ACPI Binary Tools. The second time I open it and use Dump ACPI Tables, it still needs to be downloaded.
