### ISSUE TITLE
how to use hardware-sniffer to generate hardware report on an existing hackintosh

### ISSUE THREAD

**Issue by multicollinearity** [lzhoang2801/Hardware-Sniffer#6]
I have an hackintosh with OS Monterey that was installed about 3 year ago through OpenCore. How would I use this tool to generate hardware report so I can use opcore-simplify tool? Per the instruction, this hardware-sniffer doesn't work for mac. Thank you!

**Comment by lzhoang2801** [comment]
Regarding Windows, do what is necessary as instructed/

**Comment by multicollinearity** [comment]
I am sorry, I don't understand. There is not a windows system anymore. It only has Mac OS.

**Comment by lzhoang2801** [comment]
Reinstall Windows or use Windows PE to use the Hardware Sniffer

**Comment by KaKi87** [comment]
Reinstalling Windows just for that seems like a lot. Is Windows PE like a Linux live USB but for Windows ? I can't find an ISO... Actually, what about Linux ? The README shows a link to a branch but it no longer works
