### ISSUE TITLE
Where is macOS release??

### ISSUE THREAD

**Issue by godisopensource** [lzhoang2801/Hardware-Sniffer#8]
Hi!
I wanted to use Hardware sniffer to get a JSON output to give to OpCore-Simplify. In your README file, you say that we have to run .exe file from the releases page, but then show a macOS terminal. I am currently using macOS 15 on my Hackintosh machine and do not have Windows running alongside. I thus tried to run the python script at the root of the project, which raised the issue 'OS not supported'. 
Is there a way to launch the script on macOS?? Or Linux?
Thank you for the answer.

**Comment by lzhoang2801** [comment]
Read it. https://github.com/lzhoang2801/Hardware-Sniffer#-qa
